# Kong for Kubernetes with Kong Enterprise with Enterprise features enabled and
# exposed via TLS-enabled Ingresses. Before installing:
# * Several settings (search for the string "CHANGEME") require user-provided
#   Secrets. These Secrets must be created before installation.
# * Ingresses reference example "<service>.kong.CHANGEME.example" hostnames. These must
#   be changed to an actual hostname that resolve to your proxy.
# * Ensure that your session configurations create cookies that are usable
#   across your services. The admin session configuration must create cookies
#   that are sent to both the admin API and Kong Manager, and any Dev Portal
#   instances with authentication must create cookies that are sent to both
#   the Portal and Portal API.

image:
  repository: kong/kong-gateway
  tag: "2.7.0.0-alpine"

env:
  prefix: /kong_prefix/
  database: postgres

  password:
    valueFrom:
      secretKeyRef:
        name: kong-superuser-password
        key: password

admin:
  enabled: true
  annotations:
    konghq.com/protocol: "https"
    telegraf.influxdata.com/image: telegraf:1.21-alpine
    telegraf.influxdata.com/class: "kong"
    telegraf.influxdata.com/interval: 1s
    telegraf.influxdata.com/path: /status
    telegraf.influxdata.com/port: "8100"
    telegraf.influxdata.com/scheme: http
  tls:
    enabled: true
    servicePort: 8444
    containerPort: 8444
    parameters:
    - http2

  ingress:
    enabled: true
    tls: ingress-admin-tls-secret
    hostname: admin.kong.deejiw.com
    annotations:
      kubernetes.io/ingress.class: "kong"
    path: /

proxy:
  enabled: true
  type: LoadBalancer
  annotations: {}

  http:
    enabled: true
    servicePort: 80
    containerPort: 8000
    parameters: []

  tls:
    enabled: true
    servicePort: 443
    containerPort: 8443
    parameters:
    - http2

  stream: {}

  ingress:
    enabled: false
    annotations: {}
    path: /

  externalIPs: []

enterprise:
  enabled: false

manager:
  enabled: true
  type: NodePort
  annotations:
    konghq.com/protocol: "https"

  http:
    enabled: false

  tls:
    enabled: true
    servicePort: 8445
    containerPort: 8445
    parameters:
    - http2

  ingress:
    enabled: true
    tls: ingress-manager-tls-secret
    hostname: manager.kong.deejiw.com
    annotations: {}
    path: /

  externalIPs: []

portal:
  enabled: true
  type: NodePort
  annotations:
    konghq.com/protocol: "https"

  http:
    enabled: true
    servicePort: 8003
    containerPort: 8003
    parameters: []

  tls:
    enabled: true
    servicePort: 8446
    containerPort: 8446
    parameters:
    - http2

  ingress:
    enabled: true
    tls: ingress-portal-tls-secret
    hostname: portal.kong.deejiw.com
    annotations:
      kubernetes.io/ingress.class: "kong"
    path: /

  externalIPs: []

portalapi:
  enabled: true
  type: NodePort
  annotations:
    konghq.com/protocol: "https"

  http:
    enabled: true
    servicePort: 8004
    containerPort: 8004
    parameters: []

  tls:
    enabled: true
    servicePort: 8447
    containerPort: 8447
    parameters:
    - http2

  ingress:
    enabled: true
    tls: ingress-portalapi-tls-secret
    hostname: portalapi.kong.deejiw.com
    annotations:
      kubernetes.io/ingress.class: "kong"
    path: /

  externalIPs: []

postgresql:
  enabled: true
  postgresqlUsername: kong
  postgresqlPassword: password
  postgresqlDatabase: kong
  service:
    port: 5432

ingressController:
  enabled: true
  installCRDs: false
  env:
    kong_admin_token:
      valueFrom:
        secretKeyRef:
          name: kong-superuser-password
          key: password
    admin_api_uri: ${KONG_ADMIN_IP}